### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by MagesticChicen** [Tomato6966/Discord-Js-Handler-Template#2]
I was wondering if this command handler could also have some form of permission handler for the client and the user? I think this would be a really great enhancement for what already is a great command handler. 😀
Because ultimately, permission, event, command and functions being handled is all you would ever need for a command handler

**Comment by MagesticChicen** [comment]
I was also wondering how I would set up a custom prefix using this command handler

**Comment by Tomato6966** [comment]
It should unless i haven't updated it yet. I will do it soon!
